config:
  backup: true
  banner: true
  create: true
  dotpath: .
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  link_on_import: nolink
  minversion: 0.29.5
dotfiles:
  d_bspwm:
    dst: ~/.config/bspwm
    src: config/bspwm
  d_kitty:
    dst: ~/.config/kitty
    src: config/kitty
  d_nvim:
    dst: ~/.config/nvim
    src: config/nvim
  d_polybar:
    dst: ~/.config/polybar
    src: config/polybar
  d_ranger:
    dst: ~/.config/ranger
    src: config/ranger
  d_rofi:
    dst: ~/.config/rofi
    src: config/rofi
  d_scripts:
    dst: ~/Scripts
    src: Scripts
  d_sxhkd:
    dst: ~/.config/sxhkd
    src: config/sxhkd
  d_templates:
    dst: ~/.config/wal/templates
    src: config/wal/templates
  d_yay:
    dst: ~/.config/yay
    src: config/yay
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_eslintrc.json:
    dst: ~/.eslintrc.json
    src: eslintrc.json
  f_nvidia-xinitrc:
    dst: ~/.nvidia-xinitrc
    src: nvidia-xinitrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zprofile:
    dst: ~/.zprofile
    src: zprofile
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  popinjay:
    dotfiles:
    - f_xinitrc
    - d_scripts
    - d_bspwm
    - d_kitty
    - d_nvim
    - d_polybar
    - d_ranger
    - d_rofi
    - d_sxhkd
    - d_templates
    - d_yay
    - f_compton.conf
    - f_xresources
    - f_eslintrc.json
    - f_nvidia-xinitrc
    - f_zprofile
    - f_zshrc
